# SQL Data Analysis Workshop

 This workshop is designed to help you build practical SQL skills by analyzing real-world business data. 
     
The tasks are divided into 4 levels to gradually progress from basic data retrieval to advanced analysis. Each level focuses on specific SQL concepts and challenges, allowing you to practice query writing, data filtering, aggregations, joins, and subqueries.
- Level 1: Basic SQL queries (SELECT, WHERE, ORDER BY, COUNT).
- Level 2: Aggregations (SUM, AVG, GROUP BY) and basic joins.
- Level 3: Complex joins, subqueries, and multi-table analysis.
- Level 4: Advanced analytical tasks focused on complex queries, subqueries, and aggregations..

This structured approach ensures you build confidence and expertise in SQL, preparing you for real-world data analysis challenges. ðŸš€

---
## Setup the work environment

#### 1. Library's import

In [100]:
import mysql.connector
import pandas as pd

#### 2. Connecting to the Database

In [101]:
connection=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="bikestore"
)
cursor=connection.cursor()

#### 3. Setup for SQL Magic

In [102]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [103]:
%sql mysql+pymysql://root:@localhost/bikestore


---
## Level 1: Beginner â€“ Basic Queries (using SQL Magic)

### Task 1: Retrieve all rows and columns from the customers table.

In [104]:
%sql select * from customers

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

c:\Users\alaaa\anaconda3\Lib\site-packages\sql\connection\connection.py:866: JupySQLRollbackPerformed: Found invalid transaction. JupySQL executed a ROLLBACK operation.
  warnings.warn(

1445 rows affected.

+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
| customer_id | first_name | last_name |     phone      |           email            |          street         |       city      | state | zip_code |
+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
|      1      |   Debra    |   Burks   |      None      |   debra.burks@yahoo.com    |    9273 Thorne Ave.     |   Orchard Park  |   NY  |  14127   |
|      2      |   Kasha    |    Todd   |      None      |    kasha.todd@yahoo.com    |     910 Vine Street     |     Campbell    |   CA  |  95008   |
|      3      |   Tameka   |   Fisher  |      None      |   tameka.fisher@aol.com    |  769C Honey Creek St.   |  Redondo Beach  |   CA  |  90278   |
|      4      |   Daryl    |   Spence  |      None      |    daryl.spence@aol.com    |     988 Pearl Lane      |    Uniondale    |   NY  |  11553   |
|      5      | Charolette |    Rice   | (916) 381-6003 |  charolette.rice@msn.com   |      107 River Dr.      |    Sacramento   |   CA  |  95820   |
|      6      |  Lyndsey   |    Bean   |      None      |  lyndsey.bean@hotmail.com  |      769 West Road      |     Fairport    |   NY  |  14450   |
|      7      |  Latasha   |    Hays   | (716) 986-3359 |  latasha.hays@hotmail.com  | 7014 Manor Station Rd.  |     Buffalo     |   NY  |  14215   |
|      8      | Jacquline  |   Duncan  |      None      | jacquline.duncan@yahoo.com |      15 Brown St.       | Jackson Heights |   NY  |  11372   |
|      9      |  Genoveva  |  Baldwin  |      None      |  genoveva.baldwin@msn.com  |    8550 Spruce Drive    | Port Washington |   NY  |  11050   |
|      10     |  Pamelia   |   Newman  |      None      |  pamelia.newman@gmail.com  |    476 Chestnut Ave.    |      Monroe     |   NY  |  10950   |
+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
Truncated to displaylimit of 10.

### Task 2: Retrieve customers who live in the city "New York".

In [105]:
%sql select * from customers where city="New York"

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

7 rows affected.

+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
| customer_id | first_name | last_name |     phone      |           email            |           street          |   city   | state | zip_code |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
|      16     |   Emmitt   |  Sanchez  | (212) 945-8823 | emmitt.sanchez@hotmail.com |   461 Squaw Creek Road    | New York |   NY  |  10002   |
|     178     |  Genoveva  |   Tyler   | (212) 152-6381 |  genoveva.tyler@gmail.com  |    8121 Windfall Ave.     | New York |   NY  |  10002   |
|     327     |   Sharie   |  Alvarez  | (212) 211-7621 |   sharie.alvarez@msn.com   | 987 West Leatherwood Dr.  | New York |   NY  |  10002   |
|     411     |  Octavia   |    Case   | (212) 171-1335 |    octavia.case@aol.com    |      40 Charles Road      | New York |   NY  |  10002   |
|     854     |   Phylis   |   Adkins  | (212) 325-9145 |   phylis.adkins@msn.com    |      7781 James Ave.      | New York |   NY  |  10002   |
|     927     | Guillermo  |    Hart   | (212) 652-7198 | guillermo.hart@hotmail.com |  81 Indian Summer Drive   | New York |   NY  |  10002   |
|     1016    |   Shenna   |   Benton  | (212) 578-2912 |   shenna.benton@msn.com    |   57 Shadow Brook Road    | New York |   NY  |  10002   |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+

### Task 3: Retrieve all products sorted by their price in descending order.

In [106]:
%sql select * from products order by list_price desc

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

321 rows affected.

+------------+----------------------------------------+----------+-------------+------------+------------+
| product_id |              product_name              | brand_id | category_id | model_year | list_price |
+------------+----------------------------------------+----------+-------------+------------+------------+
|    155     |     Trek Domane SLR 9 Disc - 2018      |    9     |      7      |    2018    |  11999.99  |
|    149     |     Trek Domane SLR 8 Disc - 2018      |    9     |      7      |    2018    |  7499.99   |
|     51     |    Trek Silque SLR 8 Women's - 2017    |    9     |      7      |    2017    |  6499.99   |
|    169     |        Trek Emonda SLR 8 - 2018        |    9     |      7      |    2018    |  6499.99   |
|    157     | Trek Domane SL Frameset Women's - 2018 |    9     |      7      |    2018    |  6499.99   |
|    156     |     Trek Domane SL Frameset - 2018     |    9     |      7      |    2018    |  6499.99   |
|     50     |    Trek Silque SLR 7 Women's - 2017    |    9     |      7      |    2017    |  5999.99   |
|    177     |     Trek Domane SLR 6 Disc - 2018      |    9     |      7      |    2018    |  5499.99   |
|    154     | Trek Domane SLR 6 Disc Women's - 2018  |    9     |      7      |    2018    |  5499.99   |
|    148     |      Trek Domane SL 8 Disc - 2018      |    9     |      7      |    2018    |  5499.99   |
+------------+----------------------------------------+----------+-------------+------------+------------+
Truncated to displaylimit of 10.

### Task 4: Find Orders by Status

#### Task 4.1: Retrieve all orders with status "Completed".

In [107]:
%%sql select * from orders
join order_statuses 
on orders.order_status=order_statuses.status_id
where order_statuses.status_id=4

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

1445 rows affected.

+----------+-------------+--------------+------------+---------------+--------------+----------+----------+-----------+--------------------+
| order_id | customer_id | order_status | order_date | required_date | shipped_date | store_id | staff_id | status_id | status_description |
+----------+-------------+--------------+------------+---------------+--------------+----------+----------+-----------+--------------------+
|    1     |     259     |      4       | 2016-01-01 |   2016-01-03  |  2016-01-03  |    1     |    2     |     4     |     Completed      |
|    2     |     1212    |      4       | 2016-01-01 |   2016-01-04  |  2016-01-03  |    2     |    6     |     4     |     Completed      |
|    3     |     523     |      4       | 2016-01-02 |   2016-01-05  |  2016-01-03  |    2     |    7     |     4     |     Completed      |
|    4     |     175     |      4       | 2016-01-03 |   2016-01-04  |  2016-01-05  |    1     |    3     |     4     |     Completed      |
|    5     |     1324    |      4       | 2016-01-03 |   2016-01-06  |  2016-01-06  |    2     |    6     |     4     |     Completed      |
|    6     |      94     |      4       | 2016-01-04 |   2016-01-07  |  2016-01-05  |    2     |    6     |     4     |     Completed      |
|    7     |     324     |      4       | 2016-01-04 |   2016-01-07  |  2016-01-05  |    2     |    6     |     4     |     Completed      |
|    8     |     1204    |      4       | 2016-01-04 |   2016-01-05  |  2016-01-05  |    2     |    7     |     4     |     Completed      |
|    9     |      60     |      4       | 2016-01-05 |   2016-01-08  |  2016-01-08  |    1     |    2     |     4     |     Completed      |
|    10    |     442     |      4       | 2016-01-05 |   2016-01-06  |  2016-01-06  |    2     |    6     |     4     |     Completed      |
+----------+-------------+--------------+------------+---------------+--------------+----------+----------+-----------+--------------------+
Truncated to displaylimit of 10.

#### Task 4.1: Retrieve count of orders with status "Rejected".

In [108]:
%%sql select count(orders.order_id) as RejectedOrders 
from orders
join order_statuses 
on orders.order_status=order_statuses.status_id
where order_statuses.status_id=3

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

1 rows affected.

+----------------+
| RejectedOrders |
+----------------+
|       45       |
+----------------+

### Task 5: Count how many customers exist in the customers table.

In [109]:

%sql select count(customer_id) as NumOfCustomers from customers

Running query in 'mysql+pymysql://root:***@localhost/bikestore'

1 rows affected.

+----------------+
| NumOfCustomers |
+----------------+
|      1445      |
+----------------+

---
## Level 2: Intermediate â€“ Aggregations and Basic Joins
##### (Task 1,2,3 using Pandas read_sql and Task 4,5 using execute and fetchall() in mysql.connector)

### Task 1: Calculate the total revenue (sum of list_price * quantity) from the order_items table.

In [110]:
query=""" select sum(list_price*quantity)as TotalRevenue
from order_items
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\194878474.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

   TotalRevenue
0    8578988.88

### Task 2: Calculate the average price of products in the products table.

In [111]:
query="select avg(list_price) as AvgPrice from products"
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1957635708.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

      AvgPrice
0  1520.591402

### Task 3: Retrieve the number of orders placed by each customer.

In [112]:
query="""select customers.customer_id,customers.first_name,count(orders.order_id) as NumOfOrders
from customers
join orders
on customers.customer_id=orders.customer_id
group by customers.first_name
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\4159102475.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

      customer_id first_name  NumOfOrders
0            1174      Aaron            1
1             338      Abbey            1
2              75       Abby            2
3            1224      Abram            1
4             673       Adam            2
...           ...        ...          ...
1260           81       Zina            2
1261         1432       Zona            1
1262         1052       Zora            1
1263          417    Zoraida            1
1264          630     Zulema            2

[1265 rows x 3 columns]

### Task 4: Join Orders with Customers

#### Task 4.1: Retrieve customer names along with their order IDs.

In [113]:
query="""select customers.first_name,customers.last_name,orders.order_id
from customers
join orders
on customers.customer_id=orders.customer_id
"""
cursor.execute(query)
rows=cursor.fetchall()
for row in rows:
    print(f"customer_first_name:{row[0]}, customer_last_name:{row[1]}, order_id:{row[2]}")

customer_first_name:Debra, customer_last_name:Burks, order_id:599
customer_first_name:Debra, customer_last_name:Burks, order_id:1555
customer_first_name:Debra, customer_last_name:Burks, order_id:1613
customer_first_name:Kasha, customer_last_name:Todd, order_id:692
customer_first_name:Kasha, customer_last_name:Todd, order_id:1084
customer_first_name:Kasha, customer_last_name:Todd, order_id:1509
customer_first_name:Tameka, customer_last_name:Fisher, order_id:1468
customer_first_name:Tameka, customer_last_name:Fisher, order_id:1496
customer_first_name:Tameka, customer_last_name:Fisher, order_id:1612
customer_first_name:Daryl, customer_last_name:Spence, order_id:700
customer_first_name:Daryl, customer_last_name:Spence, order_id:1259
customer_first_name:Daryl, customer_last_name:Spence, order_id:1556
customer_first_name:Charolette, customer_last_name:Rice, order_id:264
customer_first_name:Charolette, customer_last_name:Rice, order_id:571
customer_first_name:Charolette, customer_last_name:Rice, order_id:1544
customer_first_name:Lyndsey, customer_last_name:Bean, order_id:1059
customer_first_name:Lyndsey, customer_last_name:Bean, order_id:1592
customer_first_name:Lyndsey, customer_last_name:Bean, order_id:1611
customer_first_name:Latasha, customer_last_name:Hays, order_id:104
customer_first_name:Latasha, customer_last_name:Hays, order_id:1532
customer_first_name:Latasha, customer_last_name:Hays, order_id:1604
customer_first_name:Jacquline, customer_last_name:Duncan, order_id:512
customer_first_name:Jacquline, customer_last_name:Duncan, order_id:1010
customer_first_name:Jacquline, customer_last_name:Duncan, order_id:1523
customer_first_name:Genoveva, customer_last_name:Baldwin, order_id:76
customer_first_name:Genoveva, customer_last_name:Baldwin, order_id:1459
customer_first_name:Genoveva, customer_last_name:Baldwin, order_id:1593
customer_first_name:Pamelia, customer_last_name:Newman, order_id:825
customer_first_name:Pamelia, customer_last_name:Newman, order_id:1541
customer_first_name:Pamelia, customer_last_name:Newman, order_id:1609
customer_first_name:Deshawn, customer_last_name:Mendoza, order_id:1074
customer_first_name:Deshawn, customer_last_name:Mendoza, order_id:1387
customer_first_name:Deshawn, customer_last_name:Mendoza, order_id:1588
customer_first_name:Robby, customer_last_name:Sykes, order_id:108
customer_first_name:Robby, customer_last_name:Sykes, order_id:715
customer_first_name:Robby, customer_last_name:Sykes, order_id:1576
customer_first_name:Lashawn, customer_last_name:Ortiz, order_id:239
customer_first_name:Lashawn, customer_last_name:Ortiz, order_id:852
customer_first_name:Lashawn, customer_last_name:Ortiz, order_id:1527
customer_first_name:Garry, customer_last_name:Espinoza, order_id:357
customer_first_name:Garry, customer_last_name:Espinoza, order_id:419
customer_first_name:Garry, customer_last_name:Espinoza, order_id:1572
customer_first_name:Linnie, customer_last_name:Branch, order_id:1401
customer_first_name:Linnie, customer_last_name:Branch, order_id:1483
customer_first_name:Linnie, customer_last_name:Branch, order_id:1610
customer_first_name:Emmitt, customer_last_name:Sanchez, order_id:352
customer_first_name:Emmitt, customer_last_name:Sanchez, order_id:1020
customer_first_name:Emmitt, customer_last_name:Sanchez, order_id:1510
customer_first_name:Caren, customer_last_name:Stephens, order_id:246
customer_first_name:Caren, customer_last_name:Stephens, order_id:301
customer_first_name:Caren, customer_last_name:Stephens, order_id:1549
customer_first_name:Georgetta, customer_last_name:Hardin, order_id:606
customer_first_name:Georgetta, customer_last_name:Hardin, order_id:1407
customer_first_name:Georgetta, customer_last_name:Hardin, order_id:1534
customer_first_name:Lizzette, customer_last_name:Stein, order_id:1211
customer_first_name:Lizzette, customer_last_name:Stein, order_id:1234
customer_first_name:Lizzette, customer_last_name:Stein, order_id:1535
customer_first_name:Aleta, customer_last_name:Shepard, order_id:547
customer_first_name:Aleta, customer_last_name:Shepard, order_id:735
customer_first_name:Aleta, customer_last_name:Shepard, order_id:1528
customer_first_name:Tobie, customer_last_name:Little, order_id:1177
customer_first_name:Tobie, customer_last_name:Little, order_id:1409
customer_first_name:Tobie, customer_last_name:Little, order_id:1596
customer_first_name:Adelle, customer_last_name:Larsen, order_id:183
customer_first_name:Adelle, customer_last_name:Larsen, order_id:1505
customer_first_name:Kaylee, customer_last_name:English, order_id:1109
customer_first_name:Kaylee, customer_last_name:English, order_id:1479
customer_first_name:Corene, customer_last_name:Wall, order_id:185
customer_first_name:Corene, customer_last_name:Wall, order_id:1157
customer_first_name:Corene, customer_last_name:Wall, order_id:1573
customer_first_name:Regenia, customer_last_name:Vaughan, order_id:1065
customer_first_name:Regenia, customer_last_name:Vaughan, order_id:1511
customer_first_name:Theo, customer_last_name:Reese, order_id:256
customer_first_name:Theo, customer_last_name:Reese, order_id:1519
customer_first_name:Santos, customer_last_name:Valencia, order_id:634
customer_first_name:Santos, customer_last_name:Valencia, order_id:1480
customer_first_name:Jeanice, customer_last_name:Frost, order_id:1306
customer_first_name:Jeanice, customer_last_name:Frost, order_id:1533
customer_first_name:Syreeta, customer_last_name:Hendricks, order_id:665
customer_first_name:Syreeta, customer_last_name:Hendricks, order_id:1569
customer_first_name:Jamaal, customer_last_name:Albert, order_id:349
customer_first_name:Jamaal, customer_last_name:Albert, order_id:444
customer_first_name:Jamaal, customer_last_name:Albert, order_id:1553
customer_first_name:Williemae, customer_last_name:Holloway, order_id:162
customer_first_name:Williemae, customer_last_name:Holloway, order_id:350
customer_first_name:Williemae, customer_last_name:Holloway, order_id:1497
customer_first_name:Araceli, customer_last_name:Golden, order_id:159
customer_first_name:Araceli, customer_last_name:Golden, order_id:582
customer_first_name:Araceli, customer_last_name:Golden, order_id:1513
customer_first_name:Deloris, customer_last_name:Burke, order_id:575
customer_first_name:Deloris, customer_last_name:Burke, order_id:1487
customer_first_name:Deloris, customer_last_name:Burke, order_id:1607
customer_first_name:Brittney, customer_last_name:Woodward, order_id:1190
customer_first_name:Brittney, customer_last_name:Woodward, order_id:1536
customer_first_name:Guillermina, customer_last_name:Noble, order_id:1476
customer_first_name:Guillermina, customer_last_name:Noble, order_id:1484
customer_first_name:Bernita, customer_last_name:Mcdaniel, order_id:303
customer_first_name:Bernita, customer_last_name:Mcdaniel, order_id:1537
customer_first_name:Melia, customer_last_name:Brady, order_id:1295
customer_first_name:Melia, customer_last_name:Brady, order_id:1524
customer_first_name:Zelma, customer_last_name:Browning, order_id:718
customer_first_name:Zelma, customer_last_name:Browning, order_id:1525
customer_first_name:Janetta, customer_last_name:Aguirre, order_id:1322
customer_first_name:Janetta, customer_last_name:Aguirre, order_id:1550
customer_first_name:Ronna, customer_last_name:Butler, order_id:598
customer_first_name:Ronna, customer_last_name:Butler, order_id:1092
customer_first_name:Ronna, customer_last_name:Butler, order_id:1589
customer_first_name:Kathie, customer_last_name:Freeman, order_id:1161
customer_first_name:Kathie, customer_last_name:Freeman, order_id:1492
customer_first_name:Tangela, customer_last_name:Quinn, order_id:1076
customer_first_name:Tangela, customer_last_name:Quinn, order_id:1559
customer_first_name:Mozelle, customer_last_name:Carter, order_id:157
customer_first_name:Mozelle, customer_last_name:Carter, order_id:935
customer_first_name:Mozelle, customer_last_name:Carter, order_id:1601
customer_first_name:Onita, customer_last_name:Johns, order_id:1253
customer_first_name:Onita, customer_last_name:Johns, order_id:1583
customer_first_name:Bennett, customer_last_name:Armstrong, order_id:826
customer_first_name:Bennett, customer_last_name:Armstrong, order_id:1594
customer_first_name:Monika, customer_last_name:Berg, order_id:132
customer_first_name:Monika, customer_last_name:Berg, order_id:1089
customer_first_name:Monika, customer_last_name:Berg, order_id:1564
customer_first_name:Bridgette, customer_last_name:Guerra, order_id:897
customer_first_name:Bridgette, customer_last_name:Guerra, order_id:1072
customer_first_name:Bridgette, customer_last_name:Guerra, order_id:1516
customer_first_name:Cesar, customer_last_name:Jackson, order_id:1200
customer_first_name:Cesar, customer_last_name:Jackson, order_id:1577
customer_first_name:Caroll, customer_last_name:Hays, order_id:739
customer_first_name:Caroll, customer_last_name:Hays, order_id:1599
customer_first_name:Cleotilde, customer_last_name:Booth, order_id:70
customer_first_name:Cleotilde, customer_last_name:Booth, order_id:593
customer_first_name:Cleotilde, customer_last_name:Booth, order_id:1529
customer_first_name:Gertrud, customer_last_name:Rhodes, order_id:222
customer_first_name:Gertrud, customer_last_name:Rhodes, order_id:1485
customer_first_name:Tu, customer_last_name:Ramirez, order_id:1116
customer_first_name:Tu, customer_last_name:Ramirez, order_id:1501
customer_first_name:Saturnina, customer_last_name:Garner, order_id:389
customer_first_name:Saturnina, customer_last_name:Garner, order_id:1521
customer_first_name:Saturnina, customer_last_name:Garner, order_id:1608
customer_first_name:Fran, customer_last_name:Yang, order_id:519
customer_first_name:Fran, customer_last_name:Yang, order_id:1570
customer_first_name:Diana, customer_last_name:Guerra, order_id:147
customer_first_name:Diana, customer_last_name:Guerra, order_id:1602
customer_first_name:Lolita, customer_last_name:Mosley, order_id:778
customer_first_name:Lolita, customer_last_name:Mosley, order_id:1413
customer_first_name:Lolita, customer_last_name:Mosley, order_id:1597
customer_first_name:Pamala, customer_last_name:Henry, order_id:27
customer_first_name:Pamala, customer_last_name:Henry, order_id:1560
customer_first_name:Damien, customer_last_name:Dorsey, order_id:694
customer_first_name:Damien, customer_last_name:Dorsey, order_id:1542
customer_first_name:Latasha, customer_last_name:Stanley, order_id:286
customer_first_name:Latasha, customer_last_name:Stanley, order_id:1526
customer_first_name:Neil, customer_last_name:Mccall, order_id:9
customer_first_name:Neil, customer_last_name:Mccall, order_id:1565
customer_first_name:Elinore, customer_last_name:Aguilar, order_id:391
customer_first_name:Elinore, customer_last_name:Aguilar, order_id:556
customer_first_name:Elinore, customer_last_name:Aguilar, order_id:1515
customer_first_name:Alica, customer_last_name:Hunter, order_id:543
customer_first_name:Alica, customer_last_name:Hunter, order_id:1481
customer_first_name:Tenisha, customer_last_name:Lyons, order_id:1390
customer_first_name:Tenisha, customer_last_name:Lyons, order_id:1558
customer_first_name:Bobbie, customer_last_name:Foster, order_id:549
customer_first_name:Bobbie, customer_last_name:Foster, order_id:673
customer_first_name:Bobbie, customer_last_name:Foster, order_id:1493
customer_first_name:Kanesha, customer_last_name:Vega, order_id:240
customer_first_name:Kanesha, customer_last_name:Vega, order_id:1561
customer_first_name:Lorrie, customer_last_name:Becker, order_id:252
customer_first_name:Lorrie, customer_last_name:Becker, order_id:885
customer_first_name:Lorrie, customer_last_name:Becker, order_id:1520
customer_first_name:Tommie, customer_last_name:Melton, order_id:424
customer_first_name:Tommie, customer_last_name:Melton, order_id:1545
customer_first_name:Jayne, customer_last_name:Kirkland, order_id:924
customer_first_name:Jayne, customer_last_name:Kirkland, order_id:1325
customer_first_name:Jayne, customer_last_name:Kirkland, order_id:1512
customer_first_name:Katelin, customer_last_name:Kennedy, order_id:1130
customer_first_name:Katelin, customer_last_name:Kennedy, order_id:1494
customer_first_name:Tomasa, customer_last_name:Carson, order_id:1041
customer_first_name:Tomasa, customer_last_name:Carson, order_id:1551
customer_first_name:Takako, customer_last_name:Casey, order_id:1360
customer_first_name:Takako, customer_last_name:Casey, order_id:1595
customer_first_name:Petronila, customer_last_name:Norris, order_id:420
customer_first_name:Petronila, customer_last_name:Norris, order_id:1566
customer_first_name:Melanie, customer_last_name:Hayes, order_id:937
customer_first_name:Melanie, customer_last_name:Hayes, order_id:1552
customer_first_name:Georgeann, customer_last_name:Waller, order_id:464
customer_first_name:Georgeann, customer_last_name:Waller, order_id:1603
customer_first_name:Abby, customer_last_name:Gamble, order_id:1318
customer_first_name:Abby, customer_last_name:Gamble, order_id:1506
customer_first_name:Parker, customer_last_name:Prince, order_id:152
customer_first_name:Parker, customer_last_name:Prince, order_id:1543
customer_first_name:Keri, customer_last_name:Bridges, order_id:407
customer_first_name:Keri, customer_last_name:Bridges, order_id:435
customer_first_name:Keri, customer_last_name:Bridges, order_id:1563
customer_first_name:Chi, customer_last_name:Goff, order_id:801
customer_first_name:Chi, customer_last_name:Goff, order_id:1522
customer_first_name:Ashanti, customer_last_name:Parks, order_id:707
customer_first_name:Ashanti, customer_last_name:Parks, order_id:1538
customer_first_name:Sarai, customer_last_name:Mckee, order_id:34
customer_first_name:Sarai, customer_last_name:Mckee, order_id:1571
customer_first_name:Zina, customer_last_name:Bonner, order_id:679
customer_first_name:Zina, customer_last_name:Bonner, order_id:1498
customer_first_name:Lizzie, customer_last_name:Joyner, order_id:961
customer_first_name:Lizzie, customer_last_name:Joyner, order_id:1491
customer_first_name:Tiesha, customer_last_name:Daniel, order_id:327
customer_first_name:Tiesha, customer_last_name:Daniel, order_id:1502
customer_first_name:Armand, customer_last_name:Whitehead, order_id:129
customer_first_name:Armand, customer_last_name:Whitehead, order_id:1486
customer_first_name:Teofila, customer_last_name:Fischer, order_id:1283
customer_first_name:Teofila, customer_last_name:Fischer, order_id:1507
customer_first_name:Lissa, customer_last_name:Vargas, order_id:128
customer_first_name:Lissa, customer_last_name:Vargas, order_id:1495
customer_first_name:Yan, customer_last_name:Mcgowan, order_id:747
customer_first_name:Yan, customer_last_name:Mcgowan, order_id:1514
customer_first_name:Titus, customer_last_name:Bullock, order_id:418
customer_first_name:Titus, customer_last_name:Bullock, order_id:1562
customer_first_name:Arvilla, customer_last_name:Osborn, order_id:1229
customer_first_name:Arvilla, customer_last_name:Osborn, order_id:1567
customer_first_name:Marjorie, customer_last_name:Logan, order_id:561
customer_first_name:Marjorie, customer_last_name:Logan, order_id:1600
customer_first_name:Marvin, customer_last_name:Mullins, order_id:12
customer_first_name:Marvin, customer_last_name:Mullins, order_id:1546
customer_first_name:Tena, customer_last_name:Cruz, order_id:1369
customer_first_name:Tena, customer_last_name:Cruz, order_id:1508
customer_first_name:Corrina, customer_last_name:Sawyer, order_id:934
customer_first_name:Corrina, customer_last_name:Sawyer, order_id:1578
customer_first_name:Sharyn, customer_last_name:Hopkins, order_id:6
customer_first_name:Sharyn, customer_last_name:Hopkins, order_id:1482
customer_first_name:Letitia, customer_last_name:Franco, order_id:804
customer_first_name:Floretta, customer_last_name:Higgins, order_id:604
customer_first_name:Louanne, customer_last_name:Martin, order_id:867
customer_first_name:Louanne, customer_last_name:Martin, order_id:1517
customer_first_name:Violet, customer_last_name:Valenzuela, order_id:190
customer_first_name:Carie, customer_last_name:Kidd, order_id:169
customer_first_name:Kellie, customer_last_name:Franco, order_id:1405
customer_first_name:Nichelle, customer_last_name:Howell, order_id:448
customer_first_name:Marisol, customer_last_name:Goodman, order_id:588
customer_first_name:Sylvie, customer_last_name:Wilkerson, order_id:401
customer_first_name:Katharina, customer_last_name:Bates, order_id:554
customer_first_name:Katharina, customer_last_name:Bates, order_id:1579
customer_first_name:Marget, customer_last_name:Hodge, order_id:207
customer_first_name:Raul, customer_last_name:Melendez, order_id:1066
customer_first_name:Cecil, customer_last_name:Hopper, order_id:258
customer_first_name:Shae, customer_last_name:Hickman, order_id:1297
customer_first_name:Monica, customer_last_name:Sears, order_id:1411
customer_first_name:Monica, customer_last_name:Sears, order_id:1584
customer_first_name:Ollie, customer_last_name:Zimmerman, order_id:1252
customer_first_name:Ollie, customer_last_name:Zimmerman, order_id:1530
customer_first_name:Shila, customer_last_name:White, order_id:516
customer_first_name:Yuk, customer_last_name:Vega, order_id:1475
customer_first_name:Eliana, customer_last_name:Silva, order_id:1264
customer_first_name:Thalia, customer_last_name:Horne, order_id:1472
customer_first_name:Rey, customer_last_name:Lindsay, order_id:1370
customer_first_name:Merlene, customer_last_name:Vinson, order_id:531
customer_first_name:Merlene, customer_last_name:Vinson, order_id:1047
customer_first_name:Merlene, customer_last_name:Vinson, order_id:1539
customer_first_name:Dacia, customer_last_name:William, order_id:158
customer_first_name:Dacia, customer_last_name:William, order_id:173
customer_first_name:Le, customer_last_name:Wood, order_id:617
customer_first_name:Thalia, customer_last_name:Dillard, order_id:741
customer_first_name:Thalia, customer_last_name:Dillard, order_id:1606
customer_first_name:Luz, customer_last_name:House, order_id:907
customer_first_name:Luz, customer_last_name:House, order_id:1499
customer_first_name:Lucy, customer_last_name:Woods, order_id:177
customer_first_name:Lucy, customer_last_name:Woods, order_id:1557
customer_first_name:Shena, customer_last_name:Carter, order_id:1364
customer_first_name:Robena, customer_last_name:Hill, order_id:1280
customer_first_name:Robena, customer_last_name:Hill, order_id:1605
customer_first_name:Jeni, customer_last_name:Booker, order_id:738
customer_first_name:Jeni, customer_last_name:Booker, order_id:1574
customer_first_name:Herlinda, customer_last_name:Stone, order_id:1021
customer_first_name:Lavina, customer_last_name:Dejesus, order_id:1425
customer_first_name:Erlinda, customer_last_name:Nielsen, order_id:197
customer_first_name:Terrance, customer_last_name:Lynn, order_id:1284
customer_first_name:Walton, customer_last_name:Dejesus, order_id:938
customer_first_name:Wes, customer_last_name:Stanton, order_id:626
customer_first_name:Tanesha, customer_last_name:Hampton, order_id:618
customer_first_name:Boyd, customer_last_name:Irwin, order_id:372
customer_first_name:Delbert, customer_last_name:Wilkins, order_id:287
customer_first_name:Brianna, customer_last_name:Moss, order_id:184
customer_first_name:Dorthey, customer_last_name:Jackson, order_id:770
customer_first_name:Dorthey, customer_last_name:Jackson, order_id:1614
customer_first_name:Sarita, customer_last_name:Parks, order_id:1346
customer_first_name:Sarita, customer_last_name:Parks, order_id:1615
customer_first_name:Shonta, customer_last_name:Mercer, order_id:743
customer_first_name:Jone, customer_last_name:Bernard, order_id:944
customer_first_name:Jone, customer_last_name:Bernard, order_id:1590
customer_first_name:Wanita, customer_last_name:Davenport, order_id:1461
customer_first_name:Cleopatra, customer_last_name:Tate, order_id:1055
customer_first_name:Ramiro, customer_last_name:Byers, order_id:766
customer_first_name:Nicholas, customer_last_name:Vazquez, order_id:950
customer_first_name:Janae, customer_last_name:Doyle, order_id:1121

#### Task 4.2: Retrieve Customer Names with Order IDs and Total Orders

In [114]:
query="""select customers.first_name,customers.last_name,count(orders.order_id) as TotalOrders
from customers
join orders
on customers.customer_id=orders.customer_id
group by customers.first_name,customers.last_name
"""
cursor.execute(query)
rows=cursor.fetchall()
for row in rows:
    print(f"customer_first_name:{row[0]}, customer_last_name:{row[1]}, totalorders:{row[2]}")

customer_first_name:Aaron, customer_last_name:Knapp, totalorders:1
customer_first_name:Abbey, customer_last_name:Pugh, totalorders:1
customer_first_name:Abby, customer_last_name:Gamble, totalorders:2
customer_first_name:Abram, customer_last_name:Copeland, totalorders:1
customer_first_name:Adam, customer_last_name:Henderson, totalorders:1
customer_first_name:Adam, customer_last_name:Thornton, totalorders:1
customer_first_name:Addie, customer_last_name:Hahn, totalorders:1
customer_first_name:Adelaida, customer_last_name:Hancock, totalorders:1
customer_first_name:Adelle, customer_last_name:Larsen, totalorders:2
customer_first_name:Adena, customer_last_name:Blake, totalorders:1
customer_first_name:Adrien, customer_last_name:Hunter, totalorders:1
customer_first_name:Adriene, customer_last_name:Rivera, totalorders:1
customer_first_name:Adriene, customer_last_name:Rollins, totalorders:1
customer_first_name:Afton, customer_last_name:Juarez, totalorders:1
customer_first_name:Agatha, customer_last_name:Daniels, totalorders:1
customer_first_name:Agatha, customer_last_name:Melton, totalorders:1
customer_first_name:Agnes, customer_last_name:Sims, totalorders:1
customer_first_name:Agustina, customer_last_name:Lawrence, totalorders:1
customer_first_name:Ai, customer_last_name:Forbes, totalorders:1
customer_first_name:Aida, customer_last_name:Koch, totalorders:1
customer_first_name:Aide, customer_last_name:Franco, totalorders:1
customer_first_name:Aileen, customer_last_name:Marquez, totalorders:1
customer_first_name:Aimee, customer_last_name:Merritt, totalorders:1
customer_first_name:Aisha, customer_last_name:Woods, totalorders:1
customer_first_name:Alane, customer_last_name:Kennedy, totalorders:1
customer_first_name:Alane, customer_last_name:Mccarty, totalorders:1
customer_first_name:Alane, customer_last_name:Munoz, totalorders:1
customer_first_name:Alanna, customer_last_name:Barry, totalorders:1
customer_first_name:Alden, customer_last_name:Atkinson, totalorders:1
customer_first_name:Alec, customer_last_name:Peck, totalorders:1
customer_first_name:Alejandrina, customer_last_name:Hodges, totalorders:1
customer_first_name:Alejandro, customer_last_name:Haney, totalorders:1
customer_first_name:Alejandro, customer_last_name:Norman, totalorders:1
customer_first_name:Alesia, customer_last_name:Horne, totalorders:1
customer_first_name:Aleta, customer_last_name:Mack, totalorders:1
customer_first_name:Aleta, customer_last_name:Shepard, totalorders:3
customer_first_name:Aleta, customer_last_name:Stone, totalorders:1
customer_first_name:Alexandria, customer_last_name:Zamora, totalorders:1
customer_first_name:Alexis, customer_last_name:Mack, totalorders:1
customer_first_name:Alfredo, customer_last_name:Dodson, totalorders:1
customer_first_name:Alica, customer_last_name:Hunter, totalorders:2
customer_first_name:Alina, customer_last_name:Mcleod, totalorders:1
customer_first_name:Alishia, customer_last_name:Elliott, totalorders:1
customer_first_name:Alisia, customer_last_name:Albert, totalorders:1
customer_first_name:Alissa, customer_last_name:Craft, totalorders:1
customer_first_name:Alissa, customer_last_name:Hood, totalorders:1
customer_first_name:Alita, customer_last_name:Salinas, totalorders:1
customer_first_name:Allie, customer_last_name:Conley, totalorders:1
customer_first_name:Alline, customer_last_name:Beasley, totalorders:1
customer_first_name:Allison, customer_last_name:Nolan, totalorders:1
customer_first_name:Alma, customer_last_name:Peck, totalorders:1
customer_first_name:Almeta, customer_last_name:Benjamin, totalorders:1
customer_first_name:Alpha, customer_last_name:King, totalorders:1
customer_first_name:Alyse, customer_last_name:Jacobson, totalorders:1
customer_first_name:Alysha, customer_last_name:Powers, totalorders:1
customer_first_name:Alysia, customer_last_name:Nicholson, totalorders:1
customer_first_name:America, customer_last_name:Swanson, totalorders:1
customer_first_name:Ami, customer_last_name:Mcmahon, totalorders:1
customer_first_name:Amina, customer_last_name:Salazar, totalorders:1
customer_first_name:Amparo, customer_last_name:Burks, totalorders:1
customer_first_name:Ana, customer_last_name:Palmer, totalorders:1
customer_first_name:Anderson, customer_last_name:Martin, totalorders:1
customer_first_name:Andreas, customer_last_name:Herman, totalorders:1
customer_first_name:Andreas, customer_last_name:Mayer, totalorders:1
customer_first_name:Andria, customer_last_name:Rivers, totalorders:1
customer_first_name:Andy, customer_last_name:O'neill, totalorders:1
customer_first_name:Angele, customer_last_name:Castro, totalorders:1
customer_first_name:Angele, customer_last_name:Schroeder, totalorders:1
customer_first_name:Angelika, customer_last_name:Perry, totalorders:1
customer_first_name:Angelina, customer_last_name:Lloyd, totalorders:1
customer_first_name:Angelique, customer_last_name:Merrill, totalorders:1
customer_first_name:Angella, customer_last_name:Bridges, totalorders:1
customer_first_name:Angie, customer_last_name:Powers, totalorders:1
customer_first_name:Anisha, customer_last_name:Lang, totalorders:1
customer_first_name:Ann, customer_last_name:Heath, totalorders:1
customer_first_name:Annabelle, customer_last_name:Hebert, totalorders:1
customer_first_name:Annett, customer_last_name:Garrett, totalorders:1
customer_first_name:Annett, customer_last_name:Rush, totalorders:1
customer_first_name:Annis, customer_last_name:Sanchez, totalorders:1
customer_first_name:Anton, customer_last_name:Barton, totalorders:1
customer_first_name:Antonetta, customer_last_name:Rocha, totalorders:1
customer_first_name:Antony, customer_last_name:Atkinson, totalorders:1
customer_first_name:Anya, customer_last_name:Contreras, totalorders:1
customer_first_name:Ara, customer_last_name:Vazquez, totalorders:1
customer_first_name:Araceli, customer_last_name:Golden, totalorders:3
customer_first_name:Arcelia, customer_last_name:Vinson, totalorders:1
customer_first_name:Ardelia, customer_last_name:Cooley, totalorders:1
customer_first_name:Arie, customer_last_name:Hunter, totalorders:1
customer_first_name:Arielle, customer_last_name:Levine, totalorders:1
customer_first_name:Arla, customer_last_name:Ellis, totalorders:1
customer_first_name:Arlena, customer_last_name:Buckner, totalorders:1
customer_first_name:Arline, customer_last_name:Lawson, totalorders:1
customer_first_name:Armand, customer_last_name:Whitehead, totalorders:2
customer_first_name:Armando, customer_last_name:Black, totalorders:1
customer_first_name:Arminda, customer_last_name:Weber, totalorders:1
customer_first_name:Arnita, customer_last_name:Thomas, totalorders:1
customer_first_name:Aron, customer_last_name:Wiggins, totalorders:1
customer_first_name:Arvilla, customer_last_name:Osborn, totalorders:2
customer_first_name:Arvilla, customer_last_name:Weiss, totalorders:1
customer_first_name:Ashanti, customer_last_name:Hammond, totalorders:1
customer_first_name:Ashanti, customer_last_name:Parks, totalorders:2
customer_first_name:Ashely, customer_last_name:Holmes, totalorders:1
customer_first_name:Ashlee, customer_last_name:Pena, totalorders:1
customer_first_name:Ashleigh, customer_last_name:Finch, totalorders:1
customer_first_name:Ashleigh, customer_last_name:Frank, totalorders:1
customer_first_name:Ashlie, customer_last_name:Parrish, totalorders:1
customer_first_name:Ashton, customer_last_name:Lott, totalorders:1
customer_first_name:Aubrey, customer_last_name:Durham, totalorders:1
customer_first_name:Augustina, customer_last_name:Joyner, totalorders:1
customer_first_name:Augustus, customer_last_name:Schmidt, totalorders:1
customer_first_name:Augustus, customer_last_name:Steele, totalorders:1
customer_first_name:Ayana, customer_last_name:Keith, totalorders:1
customer_first_name:Ayanna, customer_last_name:Cherry, totalorders:1
customer_first_name:Ayanna, customer_last_name:Rhodes, totalorders:1
customer_first_name:Babara, customer_last_name:Ochoa, totalorders:1
customer_first_name:Bao, customer_last_name:Wade, totalorders:1
customer_first_name:Barbera, customer_last_name:Riggs, totalorders:1
customer_first_name:Barbra, customer_last_name:Dickerson, totalorders:1
customer_first_name:Barrett, customer_last_name:Sanders, totalorders:1
customer_first_name:Barry, customer_last_name:Albert, totalorders:1
customer_first_name:Barry, customer_last_name:Buckner, totalorders:1
customer_first_name:Bart, customer_last_name:Hess, totalorders:1
customer_first_name:Barton, customer_last_name:Cox, totalorders:1
customer_first_name:Barton, customer_last_name:Crosby, totalorders:1
customer_first_name:Basil, customer_last_name:Ballard, totalorders:1
customer_first_name:Basilia, customer_last_name:Thornton, totalorders:1
customer_first_name:Bea, customer_last_name:Kane, totalorders:1
customer_first_name:Beatris, customer_last_name:Joyner, totalorders:1
customer_first_name:Bee, customer_last_name:Baker, totalorders:1
customer_first_name:Bella, customer_last_name:Perez, totalorders:1
customer_first_name:Ben, customer_last_name:Stone, totalorders:1
customer_first_name:Benito, customer_last_name:Hendrix, totalorders:1
customer_first_name:Bennett, customer_last_name:Armstrong, totalorders:2
customer_first_name:Benny, customer_last_name:Bender, totalorders:1
customer_first_name:Berna, customer_last_name:Moore, totalorders:1
customer_first_name:Bernardina, customer_last_name:Cooper, totalorders:1
customer_first_name:Berneice, customer_last_name:Pollard, totalorders:1
customer_first_name:Bernetta, customer_last_name:Marquez, totalorders:1
customer_first_name:Bernetta, customer_last_name:Summers, totalorders:1
customer_first_name:Bernita, customer_last_name:Mcdaniel, totalorders:2
customer_first_name:Beryl, customer_last_name:Bennett, totalorders:1
customer_first_name:Bess, customer_last_name:Mcbride, totalorders:1
customer_first_name:Bethany, customer_last_name:Herring, totalorders:1
customer_first_name:Bettie, customer_last_name:Glover, totalorders:1
customer_first_name:Bettie, customer_last_name:Pierce, totalorders:1
customer_first_name:Bettyann, customer_last_name:Acosta, totalorders:1
customer_first_name:Bettye, customer_last_name:Espinoza, totalorders:1
customer_first_name:Bev, customer_last_name:Chang, totalorders:1
customer_first_name:Birdie, customer_last_name:Kramer, totalorders:1
customer_first_name:Blanca, customer_last_name:Hooper, totalorders:1
customer_first_name:Bobbi, customer_last_name:Banks, totalorders:1
customer_first_name:Bobbie, customer_last_name:Foster, totalorders:3
customer_first_name:Bong, customer_last_name:Hebert, totalorders:2
customer_first_name:Bonita, customer_last_name:Marshall, totalorders:1
customer_first_name:Boyce, customer_last_name:Burks, totalorders:1
customer_first_name:Boyd, customer_last_name:Irwin, totalorders:1
customer_first_name:Brain, customer_last_name:Skinner, totalorders:1
customer_first_name:Brenda, customer_last_name:Tate, totalorders:1
customer_first_name:Brent, customer_last_name:Calderon, totalorders:1
customer_first_name:Brenton, customer_last_name:Whitaker, totalorders:1
customer_first_name:Brianna, customer_last_name:Moss, totalorders:1
customer_first_name:Brianne, customer_last_name:Hays, totalorders:1
customer_first_name:Bridgette, customer_last_name:Guerra, totalorders:3
customer_first_name:Brigid, customer_last_name:Sharp, totalorders:1
customer_first_name:Brigida, customer_last_name:Larson, totalorders:1
customer_first_name:Britteny, customer_last_name:Schroeder, totalorders:1
customer_first_name:Brittney, customer_last_name:Rojas, totalorders:1
customer_first_name:Brittney, customer_last_name:Woodward, totalorders:2
customer_first_name:Brittni, customer_last_name:Green, totalorders:1
customer_first_name:Bronwyn, customer_last_name:Vargas, totalorders:1
customer_first_name:Bryce, customer_last_name:Monroe, totalorders:1
customer_first_name:Buford, customer_last_name:Bridges, totalorders:1
customer_first_name:Buford, customer_last_name:Gilbert, totalorders:1
customer_first_name:Burma, customer_last_name:Summers, totalorders:1
customer_first_name:Calandra, customer_last_name:Stanton, totalorders:1
customer_first_name:Caleb, customer_last_name:England, totalorders:1
customer_first_name:Cameron, customer_last_name:Carroll, totalorders:1
customer_first_name:Cami, customer_last_name:Williamson, totalorders:1
customer_first_name:Camila, customer_last_name:Carroll, totalorders:1
customer_first_name:Camille, customer_last_name:Harvey, totalorders:1
customer_first_name:Candelaria, customer_last_name:Coffey, totalorders:1
customer_first_name:Candis, customer_last_name:Harding, totalorders:1
customer_first_name:Caren, customer_last_name:Stephens, totalorders:3
customer_first_name:Caridad, customer_last_name:Compton, totalorders:1
customer_first_name:Carie, customer_last_name:Kidd, totalorders:1
customer_first_name:Carina, customer_last_name:Lynch, totalorders:1
customer_first_name:Carisa, customer_last_name:Carpenter, totalorders:1
customer_first_name:Carissa, customer_last_name:Cross, totalorders:1
customer_first_name:Carissa, customer_last_name:Foreman, totalorders:1
customer_first_name:Carita, customer_last_name:Salinas, totalorders:1
customer_first_name:Carlena, customer_last_name:Salinas, totalorders:1
customer_first_name:Carley, customer_last_name:Reynolds, totalorders:2
customer_first_name:Carlie, customer_last_name:Terrell, totalorders:1
customer_first_name:Carline, customer_last_name:Collier, totalorders:2
customer_first_name:Carman, customer_last_name:Hardy, totalorders:1
customer_first_name:Carmela, customer_last_name:Hays, totalorders:1
customer_first_name:Carmelina, customer_last_name:Sellers, totalorders:1
customer_first_name:Carmina, customer_last_name:Emerson, totalorders:1
customer_first_name:Carola, customer_last_name:Johns, totalorders:1
customer_first_name:Carola, customer_last_name:Mcpherson, totalorders:1
customer_first_name:Carola, customer_last_name:Rodriquez, totalorders:2
customer_first_name:Carolann, customer_last_name:Russell, totalorders:1
customer_first_name:Caroline, customer_last_name:Jenkins, totalorders:1
customer_first_name:Caroll, customer_last_name:Hays, totalorders:2
customer_first_name:Carolyne, customer_last_name:Conley, totalorders:1
customer_first_name:Carroll, customer_last_name:Kelly, totalorders:1
customer_first_name:Carson, customer_last_name:Macias, totalorders:1
customer_first_name:Carter, customer_last_name:Bentley, totalorders:1
customer_first_name:Carter, customer_last_name:Booth, totalorders:1
customer_first_name:Casey, customer_last_name:Gill, totalorders:1
customer_first_name:Casimira, customer_last_name:Chapman, totalorders:1
customer_first_name:Cassandra, customer_last_name:Nichols, totalorders:1
customer_first_name:Cassidy, customer_last_name:Clark, totalorders:1
customer_first_name:Cassie, customer_last_name:Cline, totalorders:1
customer_first_name:Cassondra, customer_last_name:Pruitt, totalorders:1
customer_first_name:Catarina, customer_last_name:Mendez, totalorders:1
customer_first_name:Catherine, customer_last_name:Miles, totalorders:1
customer_first_name:Cathey, customer_last_name:Lamb, totalorders:1
customer_first_name:Catrice, customer_last_name:Hicks, totalorders:1
customer_first_name:Cayla, customer_last_name:Johnson, totalorders:1
customer_first_name:Cecelia, customer_last_name:Gill, totalorders:1
customer_first_name:Cecil, customer_last_name:Hopper, totalorders:1
customer_first_name:Cecilia, customer_last_name:Camacho, totalorders:1
customer_first_name:Celestine, customer_last_name:Jacobs, totalorders:1
customer_first_name:Celestine, customer_last_name:Kent, totalorders:1
customer_first_name:Cesar, customer_last_name:Jackson, totalorders:2
customer_first_name:Cesar, customer_last_name:Wilkins, totalorders:1
customer_first_name:Chanel, customer_last_name:May, totalorders:1
customer_first_name:Chantay, customer_last_name:Maynard, totalorders:1
customer_first_name:Chantell, customer_last_name:Bridges, totalorders:1
customer_first_name:Charise, customer_last_name:Burt, totalorders:1
customer_first_name:Charleen, customer_last_name:Hurst, totalorders:1
customer_first_name:Charleen, customer_last_name:Joyner, totalorders:1
customer_first_name:Charlene, customer_last_name:Norris, totalorders:1
customer_first_name:Charlesetta, customer_last_name:Soto, totalorders:1
customer_first_name:Charlsie, customer_last_name:Carson, totalorders:1
customer_first_name:Charlyn, customer_last_name:Cantrell, totalorders:1
customer_first_name:Charmain, customer_last_name:Webster, totalorders:1
customer_first_name:Charolette, customer_last_name:Rice, totalorders:3
customer_first_name:Chasidy, customer_last_name:Tran, totalorders:1
customer_first_name:Chasidy, customer_last_name:Webster, totalorders:1
customer_first_name:Chauncey, customer_last_name:Donaldson, totalorders:1
customer_first_name:Chelsey, customer_last_name:Boyd, totalorders:1
customer_first_name:Chelsey, customer_last_name:Hardin, totalorders:1
customer_first_name:Cher, customer_last_name:Alston, totalorders:1
customer_first_name:Chere, customer_last_name:Alston, totalorders:1
customer_first_name:Chere, customer_last_name:Hardin, totalorders:1
customer_first_name:Chere, customer_last_name:Mcfadden, totalorders:1
customer_first_name:Cheree, customer_last_name:Hale, totalorders:1
customer_first_name:Cherelle, customer_last_name:Key, totalorders:1
customer_first_name:Cheryll, customer_last_name:Snyder, totalorders:1
customer_first_name:Chi, customer_last_name:Goff, totalorders:2
customer_first_name:Chloe, customer_last_name:Patel, totalorders:1
customer_first_name:Christel, customer_last_name:Barber, totalorders:1
customer_first_name:Christel, customer_last_name:Cardenas, totalorders:1
customer_first_name:Christia, customer_last_name:Carson, totalorders:1
customer_first_name:Christia, customer_last_name:Wilkins, totalorders:1
customer_first_name:Christiana, customer_last_name:Gross, totalorders:1
customer_first_name:Christiane, customer_last_name:Bradford, totalorders:1
customer_first_name:Christoper, customer_last_name:Gould, totalorders:1
customer_first_name:Christoper, customer_last_name:Mccall, totalorders:1
customer_first_name:Christopher, customer_last_name:Richardson, totalorders:1
customer_first_name:Cicely, customer_last_name:Deleon, totalorders:1
customer_first_name:Ciera, customer_last_name:Koch, totalorders:1
customer_first_name:Ciera, customer_last_name:Webb, totalorders:1
customer_first_name:Cinda, customer_last_name:Rocha, totalorders:1
customer_first_name:Cindi, customer_last_name:Ellis, totalorders:1
customer_first_name:Cindi, customer_last_name:Larson, totalorders:1
customer_first_name:Cindie, customer_last_name:Franklin, totalorders:1
customer_first_name:Cinthia, customer_last_name:Poole, totalorders:1
customer_first_name:Cira, customer_last_name:Downs, totalorders:1
customer_first_name:Clare, customer_last_name:Neal, totalorders:1
customer_first_name:Claris, customer_last_name:Santiago, totalorders:1
customer_first_name:Clarita, customer_last_name:Curry, totalorders:1
customer_first_name:Claudio, customer_last_name:Wise, totalorders:1
customer_first_name:Clelia, customer_last_name:Workman, totalorders:1
customer_first_name:Clementina, customer_last_name:Sargent, totalorders:1
customer_first_name:Clementine, customer_last_name:Mooney, totalorders:1
customer_first_name:Cleopatra, customer_last_name:Tate, totalorders:1
customer_first_name:Cleotilde, customer_last_name:Booth, totalorders:3
customer_first_name:Clorinda, customer_last_name:Donovan, totalorders:1
customer_first_name:Coleen, customer_last_name:Navarro, totalorders:1
customer_first_name:Coleman, customer_last_name:Boyd, totalorders:1
customer_first_name:Collen, customer_last_name:Dennis, totalorders:1
customer_first_name:Collen, customer_last_name:Hayes, totalorders:1
customer_first_name:Collene, customer_last_name:Knox, totalorders:1
customer_first_name:Collene, customer_last_name:Roman, totalorders:1
customer_first_name:Collin, customer_last_name:Webster, totalorders:1

### Task 5: Retrieve products with stock quantities less than 50.

In [115]:
query="""select products.product_name,sum(stocks.quantity)as totalquantity
from products
join stocks
on products.product_id=stocks.product_id
group by products.product_name
having totalquantity < 50
"""
cursor.execute(query)
rows=cursor.fetchall()
for row in rows:
    print(f"product_name:{row[0]}, totalquantity:{row[1]}")

product_name:Electra Amsterdam Fashion 3i Ladies' - 2017/2018, totalquantity:47
product_name:Electra Amsterdam Original 3i - 2015/2017, totalquantity:11
product_name:Electra Amsterdam Original 3i Ladies' - 2017, totalquantity:12
product_name:Electra Amsterdam Royal 8i - 2017/2018, totalquantity:45
product_name:Electra Amsterdam Royal 8i Ladies - 2018, totalquantity:26
product_name:Electra Cruiser 1 - 2016/2017/2018, totalquantity:34
product_name:Electra Cruiser 1 Ladies' - 2018, totalquantity:10
product_name:Electra Cruiser 7D Ladies' - 2016/2018, totalquantity:44
product_name:Electra Cruiser Lux 1 - 2017, totalquantity:49
product_name:Electra Cruiser Lux 3i - 2018, totalquantity:39
product_name:Electra Cruiser Lux 3i Ladies' - 2018, totalquantity:39
product_name:Electra Cruiser Lux 7D - 2018, totalquantity:43
product_name:Electra Cruiser Lux 7D Ladies' - 2018, totalquantity:32
product_name:Electra Cruiser Lux Fat Tire 7D - 2018, totalquantity:39
product_name:Electra Cyclosaurus 1 (16-inch) - Boy's - 2018, totalquantity:32
product_name:Electra Daydreamer 3i Ladies' - 2018, totalquantity:49
product_name:Electra Delivery 3i - 2016/2017/2018, totalquantity:47
product_name:Electra Girl's Hawaii 1 (20-inch) - 2015/2016, totalquantity:29
product_name:Electra Heartchya 1 (20-inch) - Girl's - 2018, totalquantity:39
product_name:Electra Koa 3i Ladies' - 2018, totalquantity:12
product_name:Electra Morningstar 3i Ladies' - 2018, totalquantity:28
product_name:Electra Moto 1 - 2016, totalquantity:31
product_name:Electra Moto 3i (20-inch) - Boy's - 2017, totalquantity:43
product_name:Electra Queen of Hearts 3i - 2018, totalquantity:24
product_name:Electra Soft Serve 1 (16-inch) - Girl's - 2018, totalquantity:44
product_name:Electra Starship 1 16" - 2018, totalquantity:38
product_name:Electra Straight 8 1 (16-inch) - Boy's - 2018, totalquantity:43
product_name:Electra Straight 8 1 (20-inch) - Boy's - 2018, totalquantity:24
product_name:Electra Straight 8 3i (20-inch) - Boy's - 2017, totalquantity:47
product_name:Electra Straight 8 3i - 2018, totalquantity:37
product_name:Electra Super Moto 8i - 2018, totalquantity:35
product_name:Electra Superbolt 1 20" - 2018, totalquantity:9
product_name:Electra Superbolt 3i 20" - 2018, totalquantity:43
product_name:Electra Sweet Ride 1 (20-inch) - Girl's - 2018, totalquantity:41
product_name:Electra Tiger Shark 1 (20-inch) - Boys' - 2018, totalquantity:44
product_name:Electra Tiger Shark 3i (20-inch) - Boys' - 2018, totalquantity:23
product_name:Electra Tiger Shark 3i - 2018, totalquantity:41
product_name:Electra Townie 7D (20-inch) - Boys' - 2017, totalquantity:38
product_name:Electra Townie Commute Go! - 2018, totalquantity:40
product_name:Electra Townie Original 1 - 2018, totalquantity:12
product_name:Electra Townie Original 1 Ladies' - 2018, totalquantity:38
product_name:Electra Townie Original 21D EQ Ladies' - 2018, totalquantity:36
product_name:Electra Townie Original 21D Ladies' - 2018, totalquantity:16
product_name:Electra Townie Original 3i EQ - 2017/2018, totalquantity:31
product_name:Electra Townie Original 3i EQ Ladies' - 2018, totalquantity:17
product_name:Electra Townie Original 7D - 2015/2016, totalquantity:43
product_name:Electra Townie Original 7D EQ - 2018, totalquantity:34
product_name:Electra Treasure 1 20" - 2018, totalquantity:48
product_name:Electra Treasure 3i 20" - 2018, totalquantity:29
product_name:Electra White Water 3i - 2018, totalquantity:43
product_name:Haro Downtown 16 - 2017, totalquantity:44
product_name:Haro Flightline One ST - 2017, totalquantity:47
product_name:Haro Shift R3 - 2017, totalquantity:41
product_name:Haro Shredder Pro 20 - 2017, totalquantity:23
product_name:Haro SR 1.2 - 2017, totalquantity:29
product_name:Heller Shagamaw Frame - 2016, totalquantity:26
product_name:Heller Shagamaw GX1 - 2018, totalquantity:30
product_name:Pure Cycles Vine 8-Speed - 2016, totalquantity:27
product_name:Pure Cycles Western 3-Speed - Women's - 2015/2016, totalquantity:34
product_name:Pure Cycles William 3-Speed - 2016, totalquantity:43
product_name:Ritchey Timberwolf Frameset - 2016, totalquantity:45
product_name:Strider Classic 12 Balance Bike - 2018, totalquantity:46
product_name:Strider Sport 16 - 2018, totalquantity:36
product_name:Sun Bicycles Biscayne Tandem 7 - 2017, totalquantity:16
product_name:Sun Bicycles Biscayne Tandem CB - 2017, totalquantity:36
product_name:Sun Bicycles Brickell Tandem 7 - 2017, totalquantity:30
product_name:Sun Bicycles Drifter 7 - 2017, totalquantity:19
product_name:Sun Bicycles Drifter 7 - Women's - 2017, totalquantity:46
product_name:Sun Bicycles ElectroLite - 2017, totalquantity:27
product_name:Sun Bicycles Lil Bolt Type-R - 2017, totalquantity:27
product_name:Sun Bicycles Lil Kitt'n - 2017, totalquantity:48
product_name:Sun Bicycles Revolutions 24 - 2017, totalquantity:37
product_name:Sun Bicycles Revolutions 24 - Girl's - 2017, totalquantity:33
product_name:Sun Bicycles Spider 3i - 2017, totalquantity:46
product_name:Sun Bicycles Streamway 3 - 2017, totalquantity:24
product_name:Sun Bicycles Streamway 7 - 2017, totalquantity:11
product_name:Surly Big Fat Dummy Frameset - 2018, totalquantity:46
product_name:Surly ECR - 2018, totalquantity:37
product_name:Surly ECR Frameset - 2018, totalquantity:37
product_name:Surly Ice Cream Truck Frameset - 2016, totalquantity:38
product_name:Surly Krampus - 2018, totalquantity:38
product_name:Surly Krampus Frameset - 2018, totalquantity:26
product_name:Surly Ogre Frameset - 2017, totalquantity:42
product_name:Surly Pack Rat - 2018, totalquantity:41
product_name:Surly Pack Rat Frameset - 2018, totalquantity:28
product_name:Surly Steamroller - 2017, totalquantity:49
product_name:Surly Straggler - 2016, totalquantity:49
product_name:Surly Troll Frameset - 2018, totalquantity:41
product_name:Surly Wednesday - 2017, totalquantity:22
product_name:Surly Wednesday Frameset - 2016, totalquantity:34
product_name:Surly Wednesday Frameset - 2017, totalquantity:32
product_name:Trek 1120 - 2018, totalquantity:41
product_name:Trek 820 - 2018, totalquantity:42
product_name:Trek Boone 5 Disc - 2018, totalquantity:48
product_name:Trek Boone 7 - 2017, totalquantity:29
product_name:Trek Boone Race Shop Limited - 2017, totalquantity:17
product_name:Trek Conduit+ - 2018, totalquantity:22
product_name:Trek Crockett 5 Disc - 2018, totalquantity:37
product_name:Trek Crockett 7 Disc - 2018, totalquantity:34
product_name:Trek CrossRip 1 - 2018, totalquantity:28
product_name:Trek CrossRip 2 - 2018, totalquantity:29
product_name:Trek CrossRip+ - 2018, totalquantity:47
product_name:Trek Domane AL 2 - 2018, totalquantity:36
product_name:Trek Domane AL 3 Women's - 2018, totalquantity:14
product_name:Trek Domane ALR 3 - 2018, totalquantity:40
product_name:Trek Domane ALR 4 Disc - 2018, totalquantity:20
product_name:Trek Domane ALR 4 Disc Women's - 2018, totalquantity:27
product_name:Trek Domane ALR 5 Disc - 2018, totalquantity:39
product_name:Trek Domane ALR 5 Gravel - 2018, totalquantity:24
product_name:Trek Domane ALR Disc Frameset - 2018, totalquantity:41
product_name:Trek Domane ALR Frameset - 2018, totalquantity:34
product_name:Trek Domane S 5 Disc - 2017, totalquantity:39
product_name:Trek Domane S 6 - 2017, totalquantity:21
product_name:Trek Domane SL 5 Disc Women's - 2018, totalquantity:34
product_name:Trek Domane SL 6 - 2017, totalquantity:16
product_name:Trek Domane SL 6 - 2018, totalquantity:42
product_name:Trek Domane SL 6 Disc - 2018, totalquantity:25
product_name:Trek Domane SL 8 Disc - 2018, totalquantity:39
product_name:Trek Domane SL Disc Frameset - 2017, totalquantity:30
product_name:Trek Domane SL Frameset - 2018, totalquantity:35
product_name:Trek Domane SLR 6 - 2018, totalquantity:18
product_name:Trek Domane SLR 6 Disc - 2018, totalquantity:30
product_name:Trek Domane SLR 6 Disc Women's - 2018, totalquantity:44
product_name:Trek Domane SLR 8 Disc - 2018, totalquantity:24
product_name:Trek Domane SLR Disc Frameset - 2018, totalquantity:35
product_name:Trek Domane SLR Frameset - 2018, totalquantity:5
product_name:Trek Emonda S 4 - 2017, totalquantity:27
product_name:Trek Emonda S 5 - 2017, totalquantity:37
product_name:Trek Emonda SL 6 Disc - 2018, totalquantity:43
product_name:Trek Emonda SLR 6 - 2018, totalquantity:31
product_name:Trek Emonda SLR 8 - 2018, totalquantity:29
product_name:Trek Farley Alloy Frameset - 2017, totalquantity:27
product_name:Trek Farley Carbon Frameset - 2018, totalquantity:41
product_name:Trek Fuel EX 5 27.5 Plus - 2017, totalquantity:25
product_name:Trek Fuel EX 5 Plus - 2018, totalquantity:39
product_name:Trek Fuel EX 8 29 - 2016, totalquantity:36
product_name:Trek Fuel EX 9.8 27.5 Plus - 2017, totalquantity:30
product_name:Trek Fuel EX 9.8 29 - 2017, totalquantity:41
product_name:Trek Kickster - 2018, totalquantity:43
product_name:Trek Kids' Dual Sport - 2018, totalquantity:34
product_name:Trek Lift+ Lowstep - 2018, totalquantity:39
product_name:Trek Madone 9 Frameset - 2018, totalquantity:43
product_name:Trek Madone 9.2 - 2017, totalquantity:43
product_name:Trek Marlin 6 - 2018, totalquantity:27
product_name:Trek MT 201 - 2018, totalquantity:43
product_name:Trek Neko+ - 2018, totalquantity:28
product_name:Trek Powerfly 5 Women's - 2018, totalquantity:17
product_name:Trek Powerfly 7 FS - 2018, totalquantity:17
product_name:Trek Precaliber 12 Girls - 2017, totalquantity:43
product_name:Trek Precaliber 16 Boy's - 2018, totalquantity:37
product_name:Trek Precaliber 16 Boys - 2017, totalquantity:39
product_name:Trek Precaliber 16 Girls - 2017, totalquantity:39
product_name:Trek Precaliber 20 6-speed Boy's - 2018, totalquantity:27
product_name:Trek Precaliber 20 Boy's - 2018, totalquantity:41
product_name:Trek Precaliber 24 (21-Speed) - Girls - 2017, totalquantity:16
product_name:Trek Precaliber 24 (7-Speed) - Boys - 2018, totalquantity:30
product_name:Trek Precaliber 24 21-speed Boy's - 2018, totalquantity:43
product_name:Trek Precaliber 24 21-speed Girl's - 2018, totalquantity:40
product_name:Trek Procal AL Frameset - 2018, totalquantity:23
product_name:Trek Procaliber 6 - 2018, totalquantity:24
product_name:Trek Remedy 29 Carbon Frameset - 2016, totalquantity:13
product_name:Trek Remedy 9.8 - 2017, totalquantity:35
product_name:Trek Remedy 9.8 27.5 - 2018, totalquantity:19
product_name:Trek Session DH 27.5 Carbon Frameset - 2017, totalquantity:32
product_name:Trek Silque SLR 8 Women's - 2017, totalquantity:12
product_name:Trek Slash 8 27.5 - 2016, totalquantity:28
product_name:Trek Super Commuter+ 8S - 2018, totalquantity:25
product_name:Trek Superfly 20 - 2018, totalquantity:37
product_name:Trek Superfly 24 - 2017/2018, totalquantity:35
product_name:Trek Verve+ Lowstep - 2018, totalquantity:40
product_name:Trek X-Caliber 8 - 2018, totalquantity:46

---

## Level 3: Advanced â€“ Complex Joins and Subqueries
(using Pandas read_sql)

### Task 1: Retrieve the Top 5 Products with the Highest Total Sales Revenue

In [116]:
query=""" select products.product_name,sum(order_items.list_price*order_items.quantity)as TotalRevenue 
from products
join order_items
on products.product_id=order_items.product_id
group by products.product_name
order by TotalRevenue desc limit 5
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1637032239.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

                    product_name  TotalRevenue
0       Trek Slash 8 27.5 - 2016     615998.46
1           Trek Conduit+ - 2016     434998.55
2       Trek Fuel EX 8 29 - 2016     414698.57
3    Surly Straggler 650b - 2016     253829.49
4  Trek Domane SLR 6 Disc - 2017     236499.57

### Task 2: Find the Customers Who Placed the Most Orders in June, November 2018

In [117]:
query=""" select customers.customer_id,customers.first_name,customers.last_name,count(orders.order_id) as TotalOrders
from customers join orders
on customers.customer_id=orders.customer_id
where orders.order_date between "2018-6-01" and "2018-6-30"
or orders.order_date between "2018-11-01" and "2018-11-30"
group by customers.customer_id,customers.first_name,customers.last_name
order by TotalOrders desc
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\2567469148.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

   customer_id first_name last_name  TotalOrders
0          135    Dorthey   Jackson            1
1            1      Debra     Burks            1
2            7    Latasha      Hays            1

### Task 3: List All Stores with Their Total Stock Quantities for All Products

In [118]:
query=""" select stores.store_name,sum(stocks.quantity) as TotalStock
from stores join stocks
on stores.store_id=stocks.store_id
group by stores.store_name
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\657380733.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

         store_name  TotalStock
0     Baldwin Bikes      4359.0
1     Rowlett Bikes      4620.0
2  Santa Cruz Bikes      4532.0

### Task 4: Retrieve Staff Members Who Work at Stores Located in a Specific State
California (CA) , New York (NY) , Texas (TX)

In [119]:
query=""" select staffs.staff_id,staffs.first_name,staffs.last_name,stores.store_name,stores.state
from staffs join stores
on staffs.store_id=stores.store_id
where stores.state in (select state from stores)
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\2259143966.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

   staff_id  first_name last_name        store_name state
0         1     Fabiola   Jackson  Santa Cruz Bikes    CA
1         2      Mireya  Copeland  Santa Cruz Bikes    CA
2         3       Genna   Serrano  Santa Cruz Bikes    CA
3         4      Virgie   Wiggins  Santa Cruz Bikes    CA
4         5    Jannette     David     Baldwin Bikes    NY
5         6   Marcelene     Boyer     Baldwin Bikes    NY
6         7      Venita    Daniel     Baldwin Bikes    NY
7         8        Kali    Vargas     Rowlett Bikes    TX
8         9       Layla   Terrell     Rowlett Bikes    TX
9        10  Bernardine   Houston     Rowlett Bikes    TX

### Task 5: Identify the Categories of Products with the Highest Total Revenue

In [120]:
query=""" select categories.category_name,sum(order_items.list_price*order_items.quantity) as TotalRevenue
from categories join products
on categories.category_id=products.category_id
join order_items
on order_items.product_id=products.product_id
group by categories.category_name 
order by TotalRevenue desc limit 1
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\2208520600.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

    category_name  TotalRevenue
0  Mountain Bikes    3030775.71

---
## Level 4: Expert â€“ Advanced Analytical Queries
(using Pandas read_sql)

### Task 1: Find the Store with the Highest Total Revenue
Retrieve the store name and total revenue (sum of list_price * quantity) across all orders.

In [121]:
query=""" select stores.store_name,sum(order_items.list_price*order_items.quantity)as TotalRevenue
from stores join orders
on stores.store_id=orders.store_id
join order_items 
on order_items.order_id=orders.order_id
group by stores.store_name
order by TotalRevenue desc limit 1
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1989031699.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

      store_name  TotalRevenue
0  Baldwin Bikes    5826242.21

### Task 2: Find all products that have never been ordered.

In [122]:
query=""" select product_id,product_name
from products 
where product_id not in(
select products.product_id from products join order_items 
on  products.product_id =order_items.product_id)
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\2079132186.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

    product_id                                    product_name
0            1                                 Trek 820 - 2016
1          121                   Surly Krampus Frameset - 2018
2          125                    Trek Kids' Dual Sport - 2018
3          154           Trek Domane SLR 6 Disc Women's - 2018
4          195            Electra Townie Go! 8i Ladies' - 2018
5          267                Trek Precaliber 12 Girl's - 2018
6          284    Electra Savannah 1 (20-inch) - Girl's - 2018
7          291  Electra Sweet Ride 1 (20-inch) - Girl's - 2018
8          316            Trek Checkpoint ALR 4 Women's - 2019
9          317                    Trek Checkpoint ALR 5 - 2019
10         318            Trek Checkpoint ALR 5 Women's - 2019
11         319             Trek Checkpoint SL 5 Women's - 2019
12         320                     Trek Checkpoint SL 6 - 2019
13         321             Trek Checkpoint ALR Frameset - 2019

### Task 3: Identify the Customers Who Placed the Fewest Orders
Retrieve customer names and their total order counts, ordered in ascending order of order count.

In [123]:
query=""" select customers.customer_id,customers.first_name,customers.last_name,count(orders.order_id) as TotalOrders
from customers join orders
on customers.customer_id=orders.customer_id
group by customers.customer_id, customers.first_name,customers.last_name
order by TotalOrders,customers.customer_id limit 5
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\2068985368.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

   customer_id first_name   last_name  TotalOrders
0           95    Letitia      Franco            1
1           96   Floretta     Higgins            1
2           98     Violet  Valenzuela            1
3           99      Carie        Kidd            1
4          100     Kellie      Franco            1

### Task 4: Analyze Monthly Revenue for the Last Year (Specific to 2017)

In [124]:
query=""" select distinct MONTH(orders.order_date) as month,sum(order_items.list_price*order_items.quantity) as MonthlyRevenue
from orders join order_items 
on orders.order_id=order_items.order_id 
where YEAR(order_date)=2017 
group by month;
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1757344520.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

    month  MonthlyRevenue
0       1       316954.77
1       2       348740.47
2       3       348177.13
3       4       254105.57
4       5       297754.66
5       6       419892.07
6       7       255727.63
7       8       322553.32
8       9       329388.68
9      10       345316.18
10     11       315881.67
11     12       291022.87

### Task 5: Find Products That Are Low in Stock Across All Stores
Identify products where the total stock quantity (across all stores) is less than 100.

In [125]:
query=""" select products.product_id,products.product_name,sum(stocks.quantity) as TotalStock
from products join stocks
on products.product_id=stocks.product_id
group by  products.product_id,products.product_name
having TotalStock < 100
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\3967965820.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

     product_id                              product_name  TotalStock
0             1                           Trek 820 - 2016        55.0
1             2        Ritchey Timberwolf Frameset - 2016        45.0
2             3           Surly Wednesday Frameset - 2016        34.0
3             4                  Trek Fuel EX 8 29 - 2016        36.0
4             5              Heller Shagamaw Frame - 2016        26.0
..          ...                                       ...         ...
308         309         Electra Townie Commute 27D - 2018        46.0
309         310  Electra Townie Commute 27D Ladies - 2018        31.0
310         311          Electra Townie Commute 8D - 2018        70.0
311         312  Electra Townie Commute 8D Ladies' - 2018        43.0
312         313  Electra Townie Original 1 Ladies' - 2018        38.0

[313 rows x 3 columns]


---

## Level 5: Additional Advanced SQL
(using Pandas read_sql)

### Task 1: Aggregate Sales by City and State
Write a query to calculate the total sales, average order value, and maximum order value for customers in each city and state.

In [128]:
query=""" select customers.city,customers.state,count(customers.customer_id) as customer_count,
sum(order_items.list_price*order_items.quantity) as Total_Sales,avg(order_items.list_price*order_items.quantity) as avg_order_value,
max(order_items.list_price*order_items.quantity) as max_order_value
from customers join orders
on customers.customer_id=orders.customer_id
join order_items
on orders.order_id=order_items.order_id
group by customers.city,customers.state
order by Total_Sales desc
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\4201366902.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

,city,state,customer_count,Total_Sales,avg_order_value,max_order_value
0,Mount Vernon,NY,60,117010.21,1950.170167,9999.98
1,Ballston Spa,NY,52,110065.34,2116.641154,11999.98
2,San Angelo,TX,53,109729.26,2070.363396,10999.98
3,Baldwinsville,NY,37,105893.45,2861.985135,12999.98
4,Howard Beach,NY,36,104250.51,2895.847500,23999.98
...,...,...,...,...,...,...
190,Copperas Cove,TX,4,3337.94,834.485000,1319.98
191,Far Rockaway,NY,5,3249.94,649.988000,899.98
192,Springfield Gardens,NY,3,1889.95,629.983333,879.98
193,Westbury,NY,2,1437.98,718.990000,898.00
194,Tonawanda,NY,2,1347.99,673.995000,858.00

### Task 2: Find Top-Selling Products in 2018
Write a query to identify the products with the highest sales volume in the year 2018.

In [129]:
query=""" select products.product_id,YEAR(orders.order_date) as order_year, products.product_name,sum(order_items.quantity) as total_unit_sold
from orders join order_items
on order_items.order_id=orders.order_id
join products 
on products.product_id = order_items.product_id
where YEAR(orders.order_date)=2018
group by products.product_id,products.product_name
order by total_unit_sold desc;
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1322830761.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

,product_id,order_year,product_name,total_unit_sold
0,86,2018,Trek Girl's Kickster - 2017,12.0
1,92,2018,Haro Shredder 20 - 2017,11.0
2,263,2018,Strider Classic 12 Balance Bike - 2018,11.0
3,235,2018,Electra Koa 3i Ladies' - 2018,11.0
4,252,2018,Electra Townie Commute Go! Ladies' - 2018,11.0
...,...,...,...,...
296,44,2018,Haro SR 1.1 - 2017,1.0
297,262,2018,Trek MT 201 - 2018,1.0
298,250,2018,Electra Townie Go! 8i - 2017/2018,1.0
299,287,2018,Electra Straight 8 1 (16-inch) - Boy's - 2018,1.0
300,10,2018,Surly Straggler - 2016,1.0

### Task 3: Calculate Month-over-Month Sales Growth
Write a query to calculate the month-over-month sales growth for the past years.

In [130]:
query=""" select YEAR(orders.order_date) as Year, MONTH(orders.order_date) as month,
sum(order_items.quantity) as unit_sold,sum(order_items.quantity*order_items.list_price) as total_sales
from orders join order_items
on order_items.order_id=orders.order_id
group by Year,month
order by Year, month;
"""
rows=pd.read_sql(query,connection)
rows

C:\Users\alaaa\AppData\Local\Temp\ipykernel_3076\1717230893.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rows=pd.read_sql(query,connection)

    Year  month  unit_sold  total_sales
0   2016      1      221.0    241184.15
1   2016      2      223.0    175768.10
2   2016      3      213.0    202157.14
3   2016      4      176.0    187223.55
4   2016      5      224.0    228701.13
5   2016      6      199.0    231120.29
6   2016      7      211.0    222854.21
7   2016      8      251.0    253130.83
8   2016      9      281.0    303282.61
9   2016     10      254.0    235051.79
10  2016     11      181.0    205315.47
11  2016     12      229.0    223695.20
12  2017      1      229.0    316954.77
13  2017      2      263.0    348740.47
14  2017      3      296.0    348177.13
15  2017      4      248.0    254105.57
16  2017      5      241.0    297754.66
17  2017      6      296.0    419892.07
18  2017      7      249.0    255727.63
19  2017      8      287.0    322553.32
20  2017      9      237.0    329388.68
21  2017     10      296.0    345316.18
22  2017     11      241.0    315881.67
23  2017     12      216.0    291022.87
24  2018      1      241.0    426301.72
25  2018      2      160.0    223941.44
26  2018      3      290.0    406701.20
27  2018      4      580.0    909179.47
28  2018      6        1.0       209.99
29  2018      7       11.0     12949.89
30  2018      8        9.0     10256.91
31  2018      9        4.0      9949.96
32  2018     10        8.0      4219.92
33  2018     11        8.0     12278.93
34  2018     12        4.0      7999.96